pull_request_rules:
  - name: Auto Merge After CI/Approve
    conditions:
#      - status-success=continuous-integration/jenkins/branch
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - label=auto-merge
    actions:
      merge:
        method: squash
        rebase_fallback: merge
        strict: smart
      delete_head_branch: {}
