version: '2.1'
orbs:
  android: circleci/android@1.0
jobs:
  test:
    executor:
      name: android/myavd
      sdk-version: '30'
      memory: 1024
    steps:
      - checkout
      - restore-build-cache
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - save-build-cache
      - accept-licenses
      - android/start-emulator-and-run-tests:
          system-image: system-images;android-29;default;x86
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
workflows:
  test:
    jobs:
      - test